### ISSUE TITLE
[Bug Report] Grouped bodies cause error

### ISSUE THREAD

**Issue by ltbysky** [NVIDIA-Omniverse/orbit#200] opened 2024-01-13 07:07 UTC
Tow rigid bodies grouped in normal Xform cause error

==== Stage structure =====

-Bot (defaultPrim)
----  Xform   #xform just for group
--------  arm  # xform with rigid body and mass
--------  leg   # xform with rigid body and mass

Error messages: 

```
2024-01-13 06:56:47 [9,127ms] [Error] [carb.events.python] RuntimeError: Failed to parse all bodies properly in the articulation.

At:
  /home/ydf/Working/code/isaacgym/orbit/source/extensions/omni.isaac.orbit/omni/isaac/orbit/assets/articulation/articulation.py(512): _initialize_impl
  /home/ydf/Working/code/isaacgym/orbit/source/extensions/omni.isaac.orbit/omni/isaac/orbit/assets/asset_base.py(254): _initialize_callback
  /home/ydf/Working/code/isaacgym/orbit/source/extensions/omni.isaac.orbit/omni/isaac/orbit/assets/asset_base.py(91): <lambda>
  /home/ydf/Working/code/isaacgym/orbit/source/extensions/omni.isaac.orbit/omni/isaac/orbit/sim/simulation_context.py(423): render
  /home/ydf/.local/share/ov/pkg/isaac_sim-2023.1.1/exts/omni.isaac.core/omni/isaac/core/simulation_context/simulation_context.py(889): play
  /home/ydf/.local/share/ov/pkg/isaac_sim-2023.1.1/exts/omni.isaac.core/omni/isaac/core/simulation_context/simulation_context.py(592): initialize_physics
  /home/ydf/.local/share/ov/pkg/isaac_sim-2023.1.1/exts/omni.isaac.core/omni/isaac/core/simulation_context/simulation_context.py(624): reset
  /home/ydf/Working/code/isaacgym/orbit/source/extensions/omni.isaac.orbit/omni/isaac/orbit/sim/simulation_context.py(352): reset
```
Remove the Xform group layer would make it work

**Comment by Mayankm96** [comment] 2024-03-07 19:28
As pointed out by @ozhanozen, this issue is a duplicate of #237 

Closing this one to keep all discussions at one place.

**Closed by Mayankm96** 2024-03-07 19:28 UTC
Labels: duplicate, question
